<S> ::= <A><B>
	{ <S>.val = <A>.val + <B>.val }

<A> ::= a | a<A><B>
	{ <A>.val = 1 }
	| { <A_1>.val = <A_2>.val + <B>.val }

<B> ::= <B>b | b | <A><A>
	{ <B_1>.val = <B_2>.val }
	| { <B>.val = 1 }
	| { <B>.val = <A>.val * <A>.val }
